server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=web_customer_tracker;encrypt=false"
    username: "sa"
    password: "sapassword"
  application:
    name: Application
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp