server:
  port: 3636
  servlet:
    context-path: /

#configuring the datasource mysql
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/dienthoai"
    username: "root"
    password: "12345678"
  application:
    name: Application
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp